- name: Playbook1
  hosts: localhost

  vars_prompt:
  - name: URL
    prompt: "ENTER URL"   
    private: no   # if no the URL while entering show

  tasks:
  - name: Print messages_1
    debug:
      msg: "{{URL}}"